#  Matrices

## 5.2 Creating a matrix 

In [1]:
m1 = [[1,2,3], [4,5,6], [7,8,9]]
print(m1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [2]:
#importing numpy package
import numpy as np
import pandas as pd

In [3]:
np.array(m1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#creating a matrix
m2 = np.array([[1,-1], [2,-2], [3,-3]])
m2

array([[ 1, -1],
       [ 2, -2],
       [ 3, -3]])

In [5]:
## transposing the matrix
np.transpose(m2)

array([[ 1,  2,  3],
       [-1, -2, -3]])

#### 5.2.1 Matrix with zeros and ones

In [6]:
#creating matrix with zeroes
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#creating a matrix with ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 5.2.2 Identity Matrix

In [8]:
#creating an identity matrix
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 5.2.3 Random number matrix

In [9]:
np.random.rand(3,3)

array([[0.60928892, 0.01641405, 0.26208112],
       [0.58377916, 0.20832604, 0.16670959],
       [0.74243909, 0.87680005, 0.87829378]])

In [10]:
np.random.randn(3,3)

array([[ 0.68934145, -1.66315914, -0.52739598],
       [ 0.47940629, -1.44007005, -1.29398803],
       [-0.1719405 , -1.23272605,  0.55883959]])

#### 5.2.4 Random integer matrix

In [4]:
ranarr = np.random.randint(0,50,10)
ranarr

array([18, 41,  6, 44, 28,  7, 39,  5,  3,  9])

In [5]:
ranarr = np.random.randint(0,50,10)
ranarr.reshape(2,5)

array([[14, 31, 38, 35, 25],
       [ 1,  4,  7, 14, 44]])

### 5.3 Accessing matrices

In [12]:
mat = np.array(([5,10,15],[20,25,30],[35,40,45]))
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
#grabbing second row
mat[1]

array([20, 25, 30])

In [15]:
#grabbing second row third element
mat[1][2]

30

In [16]:
# 2D array slicing

#select everything except 3rd element from 1st and 2nd column
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [17]:
#select bottom row of the matrix
mat[2,:]

array([35, 40, 45])

In [18]:
#selecting everything except third item from the second row
mat[:2,1 ]

array([10, 25])

### 5.4 Matrix Manipulation

#### 5.4.1 Addition

In [19]:
a = np.array(([1,3,5],[7,9,11]))
b = np.array(([2,4,6],[8,10,12]))

In [20]:
np.add(a,b)

array([[ 3,  7, 11],
       [15, 19, 23]])

#### 5.4.2 Subtraction

In [21]:
a = np.array(([1,3,5],[7,9,11]))
b = np.array(([2,4,6],[8,10,12]))

In [22]:
np.subtract(a,b)

array([[-1, -1, -1],
       [-1, -1, -1]])

In [7]:
a = np.array(([1,2],[3,4]))
b = np.array(([5,6],[7,8]))

In [8]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [11]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9,10], [11,12]])

In [12]:
np.dot(matrix1,matrix2)

array([[ 58,  64],
       [139, 154]])

### 5.5 Matrix deletion

In [13]:
mat = np.array(([5,10,15],[20,25,30],[35,40,45]))
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
np.delete(mat,[1],0)

array([[ 5, 10, 15],
       [35, 40, 45]])

In [15]:
mat = np.array(([5,10,15],[20,25,30],[35,40,45]))
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
np.delete(mat,[1],1)

array([[ 5, 15],
       [20, 30],
       [35, 45]])