# Vectors

### 6.2 Vector Creation

In [1]:
import numpy as np 

# creating list  
lst = [10,20,30,40,50] 

# Creating 1-D Horizontal Array  
vctr = np.array(lst) 

print("Vector creation") 
print(vctr) 

Vector creation
[10 20 30 40 50]


In [2]:
# creating list
lst = [[10],[20], [30],[40],[50]]

# Creating 1-D vertical Array  
vctr = np.array(lst) 

print("Vector creation") 
print(vctr) 

Vector creation
[[10]
 [20]
 [30]
 [40]
 [50]]


### 6.3 Vector Operations

#### 6.3.1 Addition

In [3]:
import numpy as np   
#Creating a list   
list1 = [10,20,30,40,50]   
list2 = [5,15,25,35,45]  
   
#Creating a vectors
v1 = np.array(list1)   
v2= np.array(list2)   
print("Vector 1:")   
print(v1)   
print("Vector 2:")   
print(v2)   
 
#addition
vadd = v1+v2  
print("Addition of two vectors:\n",vadd)  

Vector 1:
[10 20 30 40 50]
Vector 2:
[ 5 15 25 35 45]
Addition of two vectors:
 [15 35 55 75 95]


In [4]:
import numpy as np   
#Creating a list   
list1 = [5,10.2,20.2,30.2,40.2,50.2, -9]   
list2 = [-9, 5.3,15.3,25.3,35.3,45.3, 3]  

#Creating a vectors
v1 = np.array(list1)   
v2 = np.array(list2)   
print("Vector 1:")   
print(v1)   
print("Vector 2:")   
print(v2)   
 
#addition
vadd = v1+v2  
print("Addition of two vectors:\n",vadd)  

Vector 1:
[ 5.  10.2 20.2 30.2 40.2 50.2 -9. ]
Vector 2:
[-9.   5.3 15.3 25.3 35.3 45.3  3. ]
Addition of two vectors:
 [-4.  15.5 35.5 55.5 75.5 95.5 -6. ]


In [14]:
import numpy as np   
#Creating a list   
list1 = [10,20,30,40,50]   
list2 = [5,15,25,35]  
   
#Creating a vectors
v1 = np.array(list1)   
v2 = np.array(list2)   
print("Vector 1:")   
print(v1)   
print("Vector 2:")   
print(v2)   
 
#addition
vadd = v1+v2  
print("Addition of two vectors:\n",vadd) 

Vector 1:
[10 20 30 40 50]
Vector 2:
[ 5 15 25 35]


ValueError: operands could not be broadcast together with shapes (5,) (4,) 

#### 6.3.2 Subtraction

In [27]:
import numpy as np   
#Creating a list   
list1 = [10,20,30,40,50,2.5,-10]   
list2 = [5,15,25,35,45,-10,-15]  
   
#Creating a vectors
v1 = np.array(list1)   
v2= np.array(list2)   
print("Vector 1:")   
print(v1)   
print("Vector 2:")   
print(v2)   
 
#Subtraction
vsub = v1-v2  
print("Subtraction of two vectors:\n",vsub)  

Vector 1:
[ 10.   20.   30.   40.   50.    2.5 -10. ]
Vector 2:
[  5  15  25  35  45 -10 -15]
Subtraction of two vectors:
 [ 5.   5.   5.   5.   5.  12.5  5. ]


#### 6.3.3 Dot Product

In [32]:
import numpy as np 

#Creating a list  
lst1 = [10,20,30,40,50, -60] 
lst2 = [1,1,1,1,1,2]

#Creating a vectors
v1 = np.array(lst1) 
v2= np.array(lst2) 
print("Vector1") 
print(v1) 
print("Vector2") 
print(v2) 
#dot product
vdot = v1.dot(v2)
print("Dot product of two vectors: ",vdot)

Vector1
[ 10  20  30  40  50 -60]
Vector2
[1 1 1 1 1 2]
Dot product of two vectors:  30


#### 6.3.4 Vector Scalar Multiplication

In [39]:
import numpy as np   

#Creating a list 
list1 = [10,20,30,40,50,-60, 12.5] 
#Creating a vectors
v1 = np.array(list1)   
scalar = 5  
print("Vector 1")   
print(v1)   
# printing scalar value   
print("Scalar Value  : ", scalar)   
#Vector scalar multiplication   
vscalar = v1 * scalar  
print("Vector Scalar Multiplication: ",vscalar)  

Vector 1
[ 10.   20.   30.   40.   50.  -60.   12.5]
Scalar Value  :  5
Vector Scalar Multiplication:  [  50.   100.   150.   200.   250.  -300.    62.5]
