# 2.1 Data Types 

## Numbers

## Integer

In [1]:
integer = 3
print(type(integer))


<class 'int'>


In [46]:
print(integer)

3


In [48]:
integer1 = int(3.2)
print(type(integer1))

<class 'int'>


In [49]:
print(integer1)

3


## Float

In [50]:
decimal = 3.5
print(type(decimal))

<class 'float'>


In [51]:
print(decimal)

3.5


In [53]:
decimal1 = float(2)
print(type(decimal1))

<class 'float'>


In [57]:
print(decimal1)

2.0


## Complex 

In [59]:
com1 = 3+2j
print(type(com1))

<class 'complex'>


In [60]:
print(com1)

(3+2j)


In [55]:
com = complex(2,4)
print(type(com))

<class 'complex'>


In [56]:
print(com)

(2+4j)


In [2]:
(2+4j).real

2.0

In [3]:
(2+4j).imag

4.0

# String

In [62]:
text = str('Python for Maths')
print(type(text))

<class 'str'>


In [63]:
print(text)

Python for Maths


In [64]:
text1 = "Python for Maths"
print(type(text1))

<class 'str'>


In [66]:
print(text1)

Python for Maths


In [71]:
subject = 'Maths'
subject[3]

'h'

In [4]:
subject = 'Maths'
subject[-3]

't'

In [74]:
a = 1
b = 2
print(type(a>b))

<class 'bool'>


In [75]:
print(a>b)

False


In [76]:
print(type(b>a))

<class 'bool'>


In [77]:
print(b>a)

True


# 2.2 Data Structures

## List

### Creating a List

In [16]:
listitem = [1,1,2,3,5,'Square', 'Rectangle', 3.14]

print(type(listitem))

<class 'list'>


In [17]:
print(listitem)

[1, 1, 2, 3, 5, 'square', 'rectangle', 3.14]


### Accessing values in List

In [18]:
print(listitem[5])

square


In [19]:
print(listitem[-1])

3.14


### Updating List

In [20]:
listitem[5] = 'Sphere'
print(listitem)

[1, 1, 2, 3, 5, 'sphere', 'rectangle', 3.14]


In [21]:
listitem[7] = 6.28
print(listitem)

[1, 1, 2, 3, 5, 'sphere', 'rectangle', 6.28]


### Deleting list elements

In [22]:
del listitem[5] 
print(listitem)

[1, 1, 2, 3, 5, 'rectangle', 6.28]


In [23]:
listitem.remove(6.28)
print(listitem)

[1, 1, 2, 3, 5, 'rectangle']


## Tuples

### Creating Tuples

In [25]:
tup = ('fibonacci', 'pi', 3.14, 4)
print(type(tup))

<class 'tuple'>


In [26]:
tup[0] = "6.28"

TypeError: 'tuple' object does not support item assignment

### Accessing tuple values

In [3]:
tup[0]

'fibonacci'

In [4]:
tup[-1]

4

### Deleting tuple elements

In [5]:
del tup

In [6]:
print(tup)

NameError: name 'tup' is not defined

## Sets

### Creating Sets

In [39]:
numbers_even = set((2,4,6,8,10))
print(type(numbers_even))

<class 'set'>


In [40]:
numbers_odd = {1,3,5,7,9}
print(type(numbers_odd))

<class 'set'>


### Accessing values in sets

In [41]:
for num in numbers_odd:
    print(num)

1
3
5
7
9


In [42]:
print(numbers_even)

{2, 4, 6, 8, 10}


In [43]:
print(numbers_odd)

{1, 3, 5, 7, 9}


### Adding items to a set

In [44]:
numbers_even.add(12)
print(numbers_even)

{2, 4, 6, 8, 10, 12}


In [45]:
numbers_odd.update([11,13,15,17])
print(numbers_odd)

{1, 3, 5, 7, 9, 11, 13, 15, 17}


### Removing items from a set

In [46]:
print(numbers_even)

{2, 4, 6, 8, 10, 12}


In [47]:
numbers_even.discard(12)
print(numbers_even)

{2, 4, 6, 8, 10}


In [48]:
numbers_even.remove(10)
print(numbers_even)

{2, 4, 6, 8}


In [49]:
numbers_even.discard(10)
print(numbers_even)

{2, 4, 6, 8}


In [50]:
numbers_even.remove(10)
print(numbers_even)

KeyError: 10

## Dictionary

### Creating dictionary

In [51]:
shapes = {1:'Trianle', 2:"Rectangle", 3:"Square", 4:"Sphere"}
print(type(shapes))

<class 'dict'>


In [52]:
print(shapes)

{1: 'Trianle', 2: 'Rectangle', 3: 'Square', 4: 'Sphere'}


### Accessing the dictionary values

In [53]:
shapes[3]

'Square'

In [54]:
shapes['Square']

KeyError: 'Square'

#### Updating dictionary items

In [55]:
shapes[5] = 'Cube'
print(shapes)

{1: 'Trianle', 2: 'Rectangle', 3: 'Square', 4: 'Sphere', 5: 'Cube'}


In [56]:
shapes[2] = 'Hexagon'
print(shapes)

{1: 'Trianle', 2: 'Hexagon', 3: 'Square', 4: 'Sphere', 5: 'Cube'}


#### Deleting dictionary items

In [57]:
del shapes[2]
print(shapes)

{1: 'Trianle', 3: 'Square', 4: 'Sphere', 5: 'Cube'}


In [58]:
shapes.clear()
print(shapes)

{}


In [59]:
del shapes
print(shapes)

NameError: name 'shapes' is not defined

## Arrays 

### Creating an array

In [30]:
import numpy as np

In [31]:
fibo_series = np.array([1,1,2,3,5,8,13])
print(type(fibo_series))

<class 'numpy.ndarray'>


In [35]:
print(fibo_series)

[ 1  1  2  3  5  8 13]


### Accessing array elements

In [33]:
for n in fibo_series:
    print(n)

1
1
2
3
5
8
13


In [34]:
fibo_series[5]

8

In [37]:
fibo_series[:5]

array([1, 1, 2, 3, 5])

In [39]:
fibo_series[3:8]

array([ 3,  5,  8, 13])

## 2.3 Constants

In [62]:
import math as mt

### Euler's Constant

In [63]:
mt.e

2.718281828459045

### Pi Constant

In [64]:
mt.pi

3.141592653589793

### Tau Constant

In [65]:
mt.tau

6.283185307179586