# Python Packages for Mathematics

### 14.2 Math

In [2]:
import math

In [3]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

### 14.3 Numpy

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [7]:
# Create a numpy array
arr1 = np.array([1, 2, 3, 4, 5])

# Perform element-wise operations on the array
arr2 = arr1 * 2
arr3 = np.sin(arr1)
print("Original Array: ", arr1)
print("Array Multiplication: ",arr2)  
print("Sine value of array: ",arr3) 

Original Array:  [1 2 3 4 5]
Array Multiplication:  [ 2  4  6  8 10]
Sine value of array:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [8]:
# Create a 1D array from a Python list
arr1 = np.array([1, 2, 3, 4, 5])

# Create a 2D array from a list of lists
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create an array of zeros
arr3 = np.zeros((3, 4))

# Create an array of ones
arr4 = np.ones((2, 5))

# Create an array with a range of values
arr5 = np.arange(0, 10, 2)

print("1D Array:", arr1)
print("2D Array:\n", arr2)
print("Zeros Array:\n", arr3)
print("Ones Array:\n", arr4)
print("Range Array:\n", arr5)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Range Array:
 [0 2 4 6 8]


### 14.4 SymPy

In [9]:
pip install sympy

In [10]:
import sympy as sp

In [11]:
dir(sp)

['Abs',
 'AccumBounds',
 'Add',
 'Adjoint',
 'AlgebraicField',
 'AlgebraicNumber',
 'And',
 'AppliedPredicate',
 'Array',
 'AssumptionsContext',
 'Atom',
 'AtomicExpr',
 'BasePolynomialError',
 'Basic',
 'BlockDiagMatrix',
 'BlockMatrix',
 'CC',
 'CRootOf',
 'Catalan',
 'Chi',
 'Ci',
 'Circle',
 'CoercionFailed',
 'Complement',
 'ComplexField',
 'ComplexRegion',
 'ComplexRootOf',
 'Complexes',
 'ComputationFailed',
 'ConditionSet',
 'Contains',
 'CosineTransform',
 'Curve',
 'DeferredVector',
 'DenseNDimArray',
 'Derivative',
 'Determinant',
 'DiagMatrix',
 'DiagonalMatrix',
 'DiagonalOf',
 'Dict',
 'DiracDelta',
 'DisjointUnion',
 'Domain',
 'DomainError',
 'DotProduct',
 'Dummy',
 'E',
 'E1',
 'EPath',
 'EX',
 'EXRAW',
 'Ei',
 'Eijk',
 'Ellipse',
 'EmptySequence',
 'EmptySet',
 'Eq',
 'Equality',
 'Equivalent',
 'EulerGamma',
 'EvaluationFailed',
 'ExactQuotientFailed',
 'Expr',
 'ExpressionDomain',
 'ExtraneousFactors',
 'FF',
 'FF_gmpy',
 'FF_python',
 'FU',
 'FallingFactorial',
 '

In [12]:
# Define a symbolic variable
x = sp.Symbol('x')

# Define a symbolic expression
expr = x**2 + 2*x + 1

# Perform algebraic manipulation
simplified_expr = sp.simplify(expr)

# Solve an equation
solution = sp.solve(expr, x)

print(simplified_expr)  
print(solution)        

x**2 + 2*x + 1
[-1]


In [15]:
# Define symbolic variables
x, y = sp.symbols('x y')

# Define an algebraic expression
expr = x**2 + 2*x + 1

# Find the derivative of the expression with respect to x
derivative_expr = sp.diff(expr, x)

# Integrate the expression with respect to x
integral_expr = sp.integrate(expr, x)

# Solve a simple equation x^2+3x+2 = 0
equation = sp.Eq(x**2 + 3*x + 2,0)
solution = sp.solve(equation, x)

# Print the results
print("Expression:", expr)
print("Derivative:", derivative_expr)
print("Integral:", integral_expr)
print("Solution of the Equation:", solution)

Expression: x**2 + 2*x + 1
Derivative: 2*x + 2
Integral: x**3/3 + x**2 + x
Solution of the Equation: [-2, -1]


### 14.5 SciPy

In [10]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import scipy

In [1]:
import numpy as np
from scipy.optimize import minimize

# Define the objective function to minimize
def objective(x):
    return x**2 + 5 * np.sin(x)

# Initial guess for the minimum
x0 = 2.0

# Perform the optimization
result = minimize(objective, x0)

# Extract the optimized value
min_x = result.x[0]
min_y = result.fun

print("Optimized Minimum Value:")
print("x =", min_x)
print("f(x) =", min_y)


Optimized Minimum Value:
x = -1.1105105817710532
f(x) = -3.2463942726915196


In [2]:
import numpy as np
from scipy.stats import norm, ttest_ind

# Sample data for two groups
group1 = np.array([82, 87, 85, 90, 78])
group2 = np.array([75, 88, 92, 79, 85])

# Calculate mean and standard deviation
mean_group1 = np.mean(group1)
mean_group2 = np.mean(group2)
# Use ddof=1 for sample standard deviation
std_group1 = np.std(group1, ddof=1)  
std_group2 = np.std(group2, ddof=1)

print("Group 1:")
print("Mean:", mean_group1)
print("Standard Deviation:", std_group1)

print("\nGroup 2:")
print("Mean:", mean_group2)
print("Standard Deviation:", std_group2)

# Perform a two-sample t-test
t_stat, p_value = ttest_ind(group1, group2)

print("\nTwo-sample t-test:")
print("T-statistic:", t_stat)
print("P-value:", p_value)

Group 1:
Mean: 84.4
Standard Deviation: 4.61519230368573

Group 2:
Mean: 83.8
Standard Deviation: 6.833739825307955

Two-sample t-test:
T-statistic: 0.16269784336399443
P-value: 0.874790939120554


### 14.6 Statsmodel

In [4]:
pip install statsmodels

     ---------------------------------------- 9.1/9.1 MB 36.3 MB/s eta 0:00:00
     ---------------------------------------- 233.8/233.8 kB ? eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [5]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [1]:
import numpy as np
import statsmodels.api as sm

# Sample data
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

# Add constant term to the independent variable (required for OLS)
x = sm.add_constant(x)

# Fit linear regression model
model = sm.OLS(y, x).fit()

# Print model summary
print(model.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.600
Model:                            OLS   Adj. R-squared:                  0.467
Method:                 Least Squares   F-statistic:                     4.500
Date:                Mon, 31 Jul 2023   Prob (F-statistic):              0.124
Time:                        10:01:33   Log-Likelihood:                -5.2598
No. Observations:                   5   AIC:                             14.52
Df Residuals:                       3   BIC:                             13.74
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.2000      0.938      2.345      0.1

C:\Users\BalaS\anaconda3\envs\my-rdkit-env\lib\site-packages\statsmodels\stats\stattools.py:75: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)


In [3]:
import numpy as np
import statsmodels.api as sm

# Sample data
X1 = np.array([1, 2, 3, 4, 5])
X2 = np.array([2, 4, 5, 7, 6])
Y = np.array([5, 7, 8, 10, 11])

# Create a design matrix by adding a constant term to the independent variables
X = np.column_stack((X1, X2))
X = sm.add_constant(X)

# Fit multiple linear regression model
model = sm.OLS(Y, X).fit()

# Print model summary
print(model.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.995
Model:                            OLS   Adj. R-squared:                  0.990
Method:                 Least Squares   F-statistic:                     191.4
Date:                Mon, 31 Jul 2023   Prob (F-statistic):            0.00520
Time:                        10:36:01   Log-Likelihood:                 2.2606
No. Observations:                   5   AIC:                             1.479
Df Residuals:                       2   BIC:                            0.3071
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.3111      0.338      9.782      0.0

C:\Users\BalaS\anaconda3\envs\my-rdkit-env\lib\site-packages\statsmodels\stats\stattools.py:75: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)


### 14.7 Pandas

In [4]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [5]:
import pandas as pd

In [6]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p18',
 '_testing',
 '_tslib',
 '_typing',
 

In [7]:
import pandas as pd

# Create a DataFrame
data = {
    'A': [10, 20, 30, 40, 50],
    'B': [5, 15, 25, 35, 45],
    'C': [3, 6, 9, 12, 15]
}

df = pd.DataFrame(data)

# Perform basic arithmetic operations
df['Sum'] = df['A'] + df['B']
df['Product'] = df['A'] * df['C']
df['Mean'] = df.mean(axis=1)

# Calculate summary statistics
mean_col = df.mean()
sum_row = df.sum()

print("DataFrame:")
print(df)

print("\nMean for each column:")
print(mean_col)

print("\nSum for each row:")
print(sum_row)

DataFrame:
    A   B   C  Sum  Product   Mean
0  10   5   3   15       30   12.6
1  20  15   6   35      120   39.2
2  30  25   9   55      270   77.8
3  40  35  12   75      480  128.4
4  50  45  15   95      750  191.0

Mean for each column:
A           30.0
B           25.0
C            9.0
Sum         55.0
Product    330.0
Mean        89.8
dtype: float64

Sum for each row:
A           150.0
B           125.0
C            45.0
Sum         275.0
Product    1650.0
Mean        449.0
dtype: float64
