# Arrays

### 4.2 Array Creation

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
#importing NumPy
import numpy as np

#Array creation
ar = np.array([10,20,30,40])
print(ar)

#returns the type of an array
print(type(ar))

[10 20 30 40]
<class 'numpy.ndarray'>


In [1]:
#importing NumPy
import numpy as np

#0-D Array Creation
ar = np.array(4)
print(ar)

#1-D Array Creation
ar = np.array([10,20,30,40,50])
print(ar)

#2-D Array Creation
ar = np.array([[1,2,3,4],[5,6,7,8]])
print(ar)

#3-D Array Creation
ar = np. array([[[1,2,3],[5,6,7],[9,10,11]]])
print(ar)

4
[10 20 30 40 50]
[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]]


### 4.3 Accessing Array Elements

In [15]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,30,40,50])
print("Original Array", ar)

#Accessing 2nd element
print("Second Element is : ", ar[1])

Original Array [10 20 30 40 50]
Second Element is :  20


#### 4.3.1 Accessing 2-D Array Elements

In [16]:
#importing Numpy
import numpy as np

#2-D Array Creation
ar = np.array([[1,2,3,4],[5,6,7,8]])
print("Original Array : ", ar)

#Accessing 3rd element in 2nd row
print("3rd Element in 2nd row is : ", ar[1,2])

Original Array :  [[1 2 3 4]
 [5 6 7 8]]
3rd Element in 2nd row is :  7


#### 4.3.2 Accessing 3-D Array Elements

In [6]:
#importing NumPy
import numpy as np

#3-D Array Creation
ar = np. array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

print("Original Array: \n", ar)

#Accessing Elements
print("Accessed Element is : ", ar[0,1,0])

Original Array: 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Accessed Element is :  5


In [8]:
# Importing NumPy
import numpy as np

# 3-D Array Creation with 3 blocks
ar = np.array([[[1, 2], [3,4], [5,6]],
               [[7,8], [9,10], [11,12]],
               [[13,14], [15,16], [17,18]]])

print("Original Array: \n", ar)

# Accessing Elements
print("Accessed Element is : ", ar[1, 2, 1])


Original Array: 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
Accessed Element is :  12


### 4.4 Array Slicing

In [6]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,30,40,50,60,70,80])
print("Original Array: ", ar)

#Slicing
print("Sliced Array: ", ar[3:])

Original Array:  [10 20 30 40 50 60 70 80]
Sliced Array:  [40 50 60 70 80]


In [7]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,30,40,50,60,70,80])
print("Original Array: ", ar)

#Slicing
print("Sliced Array: ", ar[:5])

Original Array:  [10 20 30 40 50 60 70 80]
Sliced Array:  [10 20 30 40 50]


In [5]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,30,40,50,60,70,80])
print("Original Array: ", ar)

#Slicing
print("Sliced Array: ", ar[1:6])

Original Array:  [10 20 30 40 50 60 70 80]
Sliced Array:  [20 30 40 50 60]


In [10]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,30,40,50,60,70,80])
print("Original Array: ", ar)

#Negative Slicing
print("Sliced Array: ", ar[-4:-1])

Original Array:  [10 20 30 40 50 60 70 80]
Sliced Array:  [50 60 70]


In [12]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,30,40,50,60,70,80])
print("Original Array: ", ar)

#Slicing using Step
print("Sliced Array: ", ar[1:6:3])

Original Array:  [10 20 30 40 50 60 70 80]
Sliced Array:  [20 50]


In [9]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,30,40,50,60,70,80])
print("Original Array: ", ar)

#Slicing using Step
print("Sliced Array: ", ar[1:6:2])

Original Array:  [10 20 30 40 50 60 70 80]
Sliced Array:  [20 40 60]


In [3]:
#importing NumPy
import numpy as np

#2-D Array Creation
ar = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Original Array:\n ", ar)

#Slicing
print("Sliced Array")
print(ar[1,1:4])

Original Array:
  [[1 2 3 4]
 [5 6 7 8]]
Sliced Array
[6 7 8]


### 4.5 Array Shape and Reshaping

In [13]:
#importing NumPy
import numpy as np

#2-D Array Creation
ar = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("Original Array: ", ar)

#Shape
print(ar.shape)

Original Array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [16]:
#importing NumPy
import numpy as np

#3-D Array Creation
ar = np.array([1, 2, 3, 4], ndmin = 3)
print("Original Array: ", ar)

#Shape
print(ar.shape)

Original Array:  [[[1 2 3 4]]]
(1, 1, 4)


In [16]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,30,40,50,60,70,80,90,100])
print("Original Array", ar)

#Reshaping 1-D to 2-D
ar_reshape = ar.reshape(2,5)
print("Reshaped Array\n", ar_reshape)

Original Array [ 10  20  30  40  50  60  70  80  90 100]
Reshaped Array
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [17]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Original Array", ar)

#Reshaping 1-D to 3-D
ar_reshape = ar.reshape(3,2,2)
print("Reshaped Array\n", ar_reshape)

Original Array [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [23]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,30,40,50,60,70,80])
print("Original Array", ar)

#Reshaping 1-D to 2-D
ar_reshape = ar.reshape(2,3)
print("Reshaped Array\n", ar_reshape)

Original Array [10 20 30 40 50 60 70 80]


ValueError: cannot reshape array of size 8 into shape (2,3)

### 4.6 Array Join

In [2]:
#importing NumPy
import numpy as np

#Array Creation
ar1 = np.array([10,20,30])
ar2 = np.array([40,50,60])

#Joining two arrays
ar = np.concatenate((ar1,ar2))
print(ar)

[10 20 30 40 50 60]


In [5]:
#importing NumPy
import numpy as np

#Array Creation
ar1 = np.array([[10,20],[30,40]])
ar2 = np.array([[50,60],[70,80]])

#Joining two 2-D arrays
ar = np.concatenate((ar1,ar2))
print(ar)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


#### 4.6.1 Stacking

In [9]:
#importing NumPy
import numpy as np

#Array Creation
ar1 = np.array([10,20,30])
ar2 = np.array([40,50,60])

#Stacking of ar1 and ar2
ar = np.stack((ar1,ar2))
print(ar)

[[10 20 30]
 [40 50 60]]


In [10]:
#importing NumPy
import numpy as np

#Array Creation
ar1 = np.array([10,20,30])
ar2 = np.array([40,50,60])

#Stacking of ar1 and ar2
ar = np.hstack((ar1,ar2))
print(ar)

[10 20 30 40 50 60]


In [11]:
#importing NumPy
import numpy as np

#Array Creation
ar1 = np.array([10,20,30])
ar2 = np.array([40,50,60])

#Stacking of ar1 and ar2
ar = np.vstack((ar1,ar2))
print(ar)

[[10 20 30]
 [40 50 60]]


In [12]:
#importing NumPy
import numpy as np

#Array Creation
ar1 = np.array([10,20,30])
ar2 = np.array([40,50,60])

#Stacking of ar1 and ar2
ar = np.dstack((ar1,ar2))
print(ar)

[[[10 40]
  [20 50]
  [30 60]]]


### 4.7 Array Split

In [18]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,30,40,50,60,70,80])
print("Original Array ", ar)

#Splitted Array
ar1 = np.array_split(ar,3)
print("Splitted Array ",ar1)

Original Array  [10 20 30 40 50 60 70 80]
Splitted Array  [array([10, 20, 30]), array([40, 50, 60]), array([70, 80])]


In [21]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([[10,20],[30,40],[50,60],[70,80],[90,100]])
print("Original Array \n ", ar)

#Split 2-D Array
ar1 = np.array_split(ar,3)
print("Splitted Array \n",ar1)

Original Array 
  [[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
Splitted Array 
 [array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100]])]


In [24]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([[10,20],[30,40],[50,60],[70,80],[90,100]])
print("Original Array \n ", ar)

#Split 
ar1 = np.hsplit(ar,2)
print("Splitted Array \n",ar1)

Original Array 
  [[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
Splitted Array 
 [array([[10],
       [30],
       [50],
       [70],
       [90]]), array([[ 20],
       [ 40],
       [ 60],
       [ 80],
       [100]])]


### 4.8 Array Search

In [31]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,10,50,10,80,10,10,20])
ar1 = np.where(ar == 10)
print(ar1)

(array([0, 2, 4, 6, 7], dtype=int64),)


In [32]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([10,20,10,50,10,80,10,10,20])
ar1 = np.where(ar%2 == 0)
print(ar1)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)


### 4.9 Array Sort

In [4]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array([50,20,10,60,30,40])
print("Original Array ", ar)

#Sorting
print("Sorted Array ", np.sort(ar))

Original Array  [50 20 10 60 30 40]
Sorted Array  [10 20 30 40 50 60]


In [5]:
#importing NumPy
import numpy as np

#Array Creation
ar = np.array(['Maths', 'Calculus','Algebra', 'Geometry'])
print("Original Array ", ar)

#Sorting
print("Sorted Array ", np.sort(ar))

Original Array  ['Maths' 'Calculus' 'Algebra' 'Geometry']
Sorted Array  ['Algebra' 'Calculus' 'Geometry' 'Maths']


In [6]:
#importing NumPy
import numpy as np

#2-D Array Creation
ar = np.array([[3,1,5,2,4], [9,7,8,10,6]])
print("Original Array: ", ar)

#Sorting
print("Sorted Array ", np.sort(ar))

Original Array:  [[ 3  1  5  2  4]
 [ 9  7  8 10  6]]
Sorted Array  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
