# Solution of Equations and Eigen Value Problems

### 8.2 Linear Interpolation Method

In [14]:
#Function Definition
def f(x):
    y = x**3 - 2*x - 5
    return y
def false_position(func, a, b, tol=1e-6, max_iter=100):
    fa = func(a)
    fb = func(b)

    for i in range(max_iter):
        c = (a * fb - b * fa) / (fb - fa)
        fc = func(c)

        if abs(fc) < tol:
            return c

        if fc * fa < 0:
            b = c
            fb = fc
        else:
            a = c
            fa = fc

    raise ValueError("It doesn't converge within the maximum iterations.")
# Initial interval [0, 1]
a = 0
b = 1
# Call false_position to find the root
root = false_position(f, a, b)
print("The root is:", root)

The root is: 2.0945514208267433


### 8.3 Newton's Method

In [2]:
#Function Definition
def f(x):
    y = x**3 - 6*x + 4
    return y
def df(x):
    y = 3*x**2 - 6
    return y
def newtons_method(func, derivative, x0, tol=1e-6, max_iter=100):
    x = x0
    for i in range(max_iter):
        fx = func(x)
        if abs(fx) < tol:
            return x
        
        # Update x using Newton's method
        x = x - fx / derivative(fx)

    raise ValueError("It doesn't converge within the maximum iterations.")

# Initial guess x0 = 1
x0 = 1

# Call newtons_method to find the root
root = newtons_method(f, df, x0)

print("The root is:", root)

The root is: 0.7320507127756016


### 8.4 Gaussian Elimination Method

In [3]:
import numpy as np

def gauss_elimination(A, B):
    n = len(B)
    # Convert the coefficient matrix and constant vector to 'float64' data type
    A = A.astype(np.float64)
    B = B.astype(np.float64)
    
    # Augment the coefficient matrix A with the column vector B
    augmented_matrix = np.hstack((A, B.reshape(-1, 1)))

    for i in range(n):
        # Find the pivot row 
        #(the row with the largest absolute value in the current column)
        pivot_row = np.argmax(np.abs(augmented_matrix[i:, i])) + i

        # Swap the current row with the pivot row
        augmented_matrix[[i, pivot_row]] = augmented_matrix[[pivot_row, i]]

        # Make the pivot element 1 
        #by dividing the current row by the pivot element
        pivot = augmented_matrix[i, i]
        augmented_matrix[i] /= pivot

        # Eliminate other elements in the current column 
        #by subtracting multiples of the pivot row
        for j in range(i + 1, n):
            factor = augmented_matrix[j, i]
            augmented_matrix[j] -= factor * augmented_matrix[i]

    # Back-substitution to find the values of the variables
    X = np.zeros(n)
    for i in range(n - 1, -1, -1):
        X[i] = augmented_matrix[i, -1]
        for j in range(i + 1, n):
            X[i] =X[i] - augmented_matrix[i, j] * X[j]
    return X

# Example system of linear equations:
# x + 2y + z = 3
# 2x + 3y + 3z = 10
# 3x - y + 2z = 13

A = np.array([[1, 2, 1],
              [2, 3, 3],
              [3, -1, 2]])

B = np.array([3, 10, 13])

# Solve the system of equations using Gauss elimination
solution = gauss_elimination(A, B)

print("Solution:")
print(solution)

Solution:
[ 2. -1.  3.]


### 8.5 Gauss Jordan Method

In [24]:
import numpy as np

def gauss_jordan(A, B):
    n = len(B)
    # Convert the coefficient matrix and constant vector to 'float64' data type
    A = A.astype(np.float64)
    B = B.astype(np.float64)

    # Augment the coefficient matrix A with the column vector B
    augmented_matrix = np.hstack((A, B.reshape(-1, 1)))

    for i in range(n):
        # Make the pivot element 1 
        #by dividing the current row by the pivot element
        pivot = augmented_matrix[i, i]
        augmented_matrix[i] /= pivot

        # Eliminate other elements in the current column
        for j in range(n):
            if i != j:
                factor = augmented_matrix[j, i]
                augmented_matrix[j] -= factor * augmented_matrix[i]

    # Extract the solutions (rightmost column) from the augmented matrix
    X = augmented_matrix[:, -1]

    return X

# Example system of linear equations:
#x1 + x2 + x3 + 4x4 = -6
#x1 + 7x2 + x3 + x4 = 12
#x1 + x2 + 6x3 + x4 = -5
#5x1 + x2 + x3 + x4 = 4

A = np.array([[1,1,1,4],
              [1,7,1,1],
              [1,1,6,1],
              [5,1,1,1]])

B = np.array([-6,12,-5,4])

# Solve the system of equations using Gauss-Jordan method
solution = gauss_jordan(A, B)

print("Solution:")
print(solution)

Solution:
[ 1.  2. -1. -2.]


### 8.6 Gauss Jacobi Method

In [26]:
import numpy as np

def gauss_jacobi(A, B, tol=1e-6, max_iter=100):
    n = len(B)
    X = np.zeros(n)
    X_prev = np.zeros(n)

    for _ in range(max_iter):
        for i in range(n):
            # Split the coefficient matrix A into 
            # diagonal and off-diagonal parts
            diag_element = A[i, i]
            off_diag_elements = A[i, :].copy()
            off_diag_elements[i] = 0

            # Calculate the current variable's value using 
            # the Jacobi update formula
            X[i] = (B[i] - np.dot(off_diag_elements, X_prev)) / diag_element

        # Check for convergence
        if np.all(np.abs(X - X_prev) < tol):
            break

        # Update the previous iteration's variable values for the next iteration
        X_prev = X.copy()
    else:
        raise ValueError("It doesn't converge within the maximum iterations.")

    return X

# Example system of linear equations:
# 10x - 5y -2z = 3
# 4x - 10y + 3z = -3
# x + 6y + 10z = -3

A = np.array([[10, -5, -2],
              [4, -10, 3],
              [1, 6, 10]])

B = np.array([3, -3, -3])

# Solve the system of equations using Gauss-Jacobi method
solution = gauss_jacobi(A, B)

print("Solution:")
print(solution)


Solution:
[ 0.3414867   0.28504262 -0.50517454]


### 8.7 Gauss Seidel Method

In [28]:
import numpy as np

def gauss_seidel(A, B, tol=1e-6, max_iter=100):
    n = len(B)
    X = np.zeros(n)

    for _ in range(max_iter):
        for i in range(n):
            # Split the coefficient matrix A into 
            # diagonal and off-diagonal parts
            diag_element = A[i, i]
            off_diag_elements = A[i, :].copy()
            off_diag_elements[i] = 0

            # Calculate the current variable's value using 
            # the Gauss-Seidel update formula
            X[i] = (B[i] - np.dot(off_diag_elements, X)) / diag_element

        # Check for convergence
        if np.all(np.abs(A @ X - B) < tol):
            break

    else:
        raise ValueError("It doesn't converge within the maximum iterations.")

    return X

# Example system of linear equations:
# 8x - 3y + 2z = 20
# 4x + 11y -z = 33
# 6x + 3y + 12z = 35

A = np.array([[8, -3, 2],
              [4, 11, -1],
              [6, 3, 12]])

B = np.array([20, 33, 35])

# Solve the system of equations using Gauss-Seidel method
solution = gauss_seidel(A, B)

print("Solution:")
print(solution)

Solution:
[3.01675484 1.98589067 0.91181658]


### 8.8 Inverse of Matrix by Gauss Elimination Method

In [36]:
import numpy as np

def gauss_elimination_inverse(A):
    n = A.shape[0]
    
    # Create an augmented matrix [A|I], where I is the identity matrix
    augmented_matrix = np.hstack((A, np.eye(n)))

    for i in range(n):
        # Make the pivot element 1 by 
        # dividing the current row by the pivot element
        pivot = augmented_matrix[i, i]
        augmented_matrix[i] /= pivot

        # Eliminate other elements in the current column
        for j in range(n):
            if i != j:
                factor = augmented_matrix[j, i]
                augmented_matrix[j] -= factor * augmented_matrix[i]

    # Extract the right-hand side (rightmost columns) of the augmented matrix, 
    # which is the inverse of A
    inverse_A = augmented_matrix[:, n:]

    return inverse_A

# Example matrix to find the inverse of:
A = np.array([[1,1,1],
              [0,1,-2],
              [-1,1,1]])

# Find the inverse of matrix A using Gauss elimination
inverse_A = gauss_elimination_inverse(A)

print("Inverse of A:")
print(inverse_A)

Inverse of A:
[[ 0.5         0.         -0.5       ]
 [ 0.33333333  0.33333333  0.33333333]
 [ 0.16666667 -0.33333333  0.16666667]]


### 8.9 Eigen value of a Matrix by Power Method

In [38]:
import numpy as np

def power_iteration(A, tol=1e-6, max_iter=1000):
    n = A.shape[0]
    
    # Initial random guess for the dominant eigenvector
    v = np.random.rand(n)

    for _ in range(max_iter):
        # Perform matrix-vector multiplication
        Av = A @ v

        # Calculate the eigenvalue estimate as the maximum element of Av
        eigenvalue = np.max(np.abs(Av))

        # Normalize the eigenvector estimate
        v_next = Av / eigenvalue

        # Check for convergence
        if np.linalg.norm(v_next - v) < tol:
            break

        v = v_next

    else:
        raise ValueError("It doesn't converge within the maximum iterations.")

    return eigenvalue, v

# Example matrix to find the dominant eigenvalue and eigenvector of:
A = np.array([[1, 2],
              [3, 4]])

# Find the dominant eigenvalue and eigenvector using power iteration
dominant_eigenvalue, dominant_eigenvector = power_iteration(A)

print("Dominant Eigenvalue:", dominant_eigenvalue)
print("Dominant Eigenvector:", dominant_eigenvector)

Dominant Eigenvalue: 5.372279703113138
Dominant Eigenvector: [0.45742657 1.        ]
